services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: java_app
    depends_on:
      - db

volumes:
  pgdata:
